-- 대여 횟수가 많은 자동차들의 월별 대여 횟수
-- https://school.programmers.co.kr/learn/courses/30/lessons/151139
WITH cars AS (
    SELECT *, MONTH(START_DATE) AS MONTH
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
)

SELECT MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CARS
WHERE CAR_ID IN(SELECT CAR_ID FROM CARS GROUP BY CAR_ID HAVING COUNT(CAR_ID) >= 5)
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC;